/**
 * @fileoverview Blender 5.0 `.glb` 3D Model Manager for **Genesis Bastion** (Phase 10).
 *
 * Preloads, caches, clones, tints, and animates the 14 subdivided & smooth-shaded PBR `.glb`
 * 3D models generated by Blender 5.0 (`scripts/generate-blender-models.py` -> `public/assets/models/*.glb`).
 * Supports real-time toggling (`[J]` / HUD button) between the sculpted Blender `.glb` models
 * and the classic procedural Three.js meshes across all active entities in the scene, while
 * preserving gameplay overlays (HP bars, Patient Zero diamonds, juvenile badges), Mendelian
 * mutation attachments, and Hero elemental weapon appearances.
 *
 * Includes a headless Node.js guard (`typeof window !== 'undefined'`) so `npm run dry-run`
 * executes with zero network errors and full hierarchical node coverage.
 */

import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { CONFIG } from '../config.js';
import { logger } from '../utils/logger.js';

/**
 * Manifest of all 14 Blender 5.0 `.glb` models in `public/assets/models/`.
 * @type {Record<string, string>}
 */
export const BLENDER_MODEL_MANIFEST = {
  hero_guardian: 'assets/models/hero_guardian.glb',
  npc_survivor: 'assets/models/npc_survivor.glb',
  goblin: 'assets/models/goblin.glb',
  orc: 'assets/models/orc.glb',
  troll: 'assets/models/troll.glb',
  wolf: 'assets/models/wolf.glb',
  lion: 'assets/models/lion.glb',
  vulture: 'assets/models/vulture.glb',
  dragon: 'assets/models/dragon.glb',
  shark: 'assets/models/shark.glb',
  giant_mole: 'assets/models/giant_mole.glb',
  deer: 'assets/models/deer.glb',
  rabbit: 'assets/models/rabbit.glb',
  bastion_monolith: 'assets/models/bastion_monolith.glb',
};

/** Standard articulated node names exported by `scripts/generate-blender-models.py`. */
const LIMB_NODE_NAMES = [
  'Body',
  'Head',
  'LeftArm',
  'RightArm',
  'LeftLeg',
  'RightLeg',
  'LeftWing',
  'RightWing',
  'Tail',
  'Weapon',
  'HeroBlade',
  'HeroVisor',
  'AmphibiousLeg_FL',
  'AmphibiousLeg_FR',
];

/** Default species color fallbacks for genetic/hybrid tinting. */
const SPECIES_FALLBACK_COLORS = {
  goblin: { color: 0x5c8a3c, accentColor: 0x9ab858 },
  orc: { color: 0x3f6a34, accentColor: 0x8f4426 },
  troll: { color: 0x3b5249, accentColor: 0x6c7a72 },
  wolf: { color: 0x626a73, accentColor: 0x9aa4b0 },
  lion: { color: 0xc9933b, accentColor: 0x5c3112 },
  vulture: { color: 0x4a3b39, accentColor: 0xb86f52 },
  dragon: { color: 0x8f2424, accentColor: 0xff6b1a },
  shark: { color: 0x2c5282, accentColor: 0x90cdf4 },
  giant_mole: { color: 0x5d4037, accentColor: 0xf48fb1 },
  deer: { color: 0xb87333, accentColor: 0xf5e6d3 },
  rabbit: { color: 0xe8e4d9, accentColor: 0xffb6c1 },
};

/**
 * Converts a color value into a `THREE.Color` instance.
 * @param {number|string|THREE.Color} val
 * @param {number} fallbackHex
 * @returns {THREE.Color}
 */
function toColor(val, fallbackHex = 0x668855) {
  if (val instanceof THREE.Color) return val.clone();
  if (typeof val === 'number' && !Number.isNaN(val)) return new THREE.Color(val);
  if (typeof val === 'string') {
    try {
      return new THREE.Color(val);
    } catch {
      return new THREE.Color(fallbackHex);
    }
  }
  return new THREE.Color(fallbackHex);
}

/**
 * Extracts normalized mutation ID strings from a genome.
 * @param {Object} [genome]
 * @returns {string[]}
 */
function getMutationIds(genome) {
  if (!genome || !Array.isArray(genome.mutations)) return [];
  return genome.mutations.map((m) => (typeof m === 'string' ? m : m?.id)).filter(Boolean);
}

/**
 * Manages preloading, caching, cloning, genetic/elemental material tinting, real-time mode toggling,
 * and limb animation for all 14 Blender 5.0 `.glb` 3D assets.
 */
export class BlenderModelManager {
  constructor() {
    /** @type {boolean} Active 3D rendering mode (`true` = Blender `.glb` models, `false` = classic procedural) */
    this.blenderMode = true;

    /** @type {Map<string, THREE.Group>} Cached master `.glb` scene templates keyed by model ID */
    this.templates = new Map();

    /**
     * Shared material cache keyed by `${modelKey}|${role || ''}|${primaryId}|${secondaryId}|${mutationIds.join(',')}`
     * to prevent per-instance material cloning and WebGL shader uniform overhead.
     * @type {Map<string, Map<THREE.Material, THREE.Material>>}
     */
    this.materialCache = new Map();

    /** @type {Set<THREE.Group>} Registered live entity groups for instant mode toggling */
    this.registeredGroups = new Set();

    /** @type {Promise<Object>|null} Active or completed preload promise */
    this._preloadPromise = null;

    /** @type {boolean} Whether all 14 models have finished loading */
    this.isLoaded = false;

    /** @type {number} Number of models loaded so far */
    this.loadedCount = 0;

    /** @type {Set<Function>} Optional listeners notified when `blenderMode` changes */
    this.modeListeners = new Set();

    /** @type {GLTFLoader|null} Lazy-instantiated browser GLTFLoader */
    this._loader = null;
  }

  /**
   * Returns whether Blender `.glb` 3D model mode is currently enabled.
   * @returns {boolean}
   */
  isBlenderModeEnabled() {
    return Boolean(this.blenderMode);
  }

  /**
   * Subscribes a callback `(enabled: boolean) => void` to Blender mode changes.
   * @param {Function} fn
   * @returns {Function} Unsubscribe function.
   */
  onModeChange(fn) {
    if (typeof fn === 'function') {
      this.modeListeners.add(fn);
    }
    return () => this.modeListeners.delete(fn);
  }

  /**
   * Switches between Blender `.glb` 3D models (`true`) and classic procedural meshes (`false`)
   * in real time across all registered entities in the scene.
   *
   * @param {boolean} enabled
   * @returns {boolean} The updated `blenderMode` state.
   */
  setBlenderMode(enabled) {
    const nextMode = Boolean(enabled);
    this.blenderMode = nextMode;

    for (const group of Array.from(this.registeredGroups)) {
      if (!group) {
        this.registeredGroups.delete(group);
        continue;
      }
      this._applyModeVisibilityToGroup(group);
    }

    logger.info(
      'BLENDER_3D',
      `🎨 Mode Modèles 3D basculé sur : ${this.blenderMode ? 'BLENDER 5.0 (.glb PBR)' : 'PROCÉDURAL CLASSIQUE (Three.js)'}`,
      {
        blenderMode: this.blenderMode,
        registeredEntities: this.registeredGroups.size,
        loadedTemplates: this.templates.size,
      }
    );

    for (const listener of this.modeListeners) {
      try {
        listener(this.blenderMode);
      } catch (err) {
        logger.warn('BLENDER_3D', 'Erreur dans un listener onModeChange', err);
      }
    }

    return this.blenderMode;
  }

  /**
   * Toggles between Blender `.glb` 3D models and classic procedural meshes.
   * @returns {boolean} The new `blenderMode` state.
   */
  toggleBlenderMode() {
    return this.setBlenderMode(!this.blenderMode);
  }

  /**
   * Resolves the manifest model key (`'hero_guardian'`, `'npc_survivor'`, `'goblin'`, etc.)
   * for a creature or structure specification.
   *
   * @param {Object} [params={}]
   * @returns {string}
   */
  getModelKeyForSpec(params = {}) {
    const type = params.type || 'enemy';
    if (type === 'player' || type === 'hero') return 'hero_guardian';
    if (type === 'npc') return 'npc_survivor';
    if (type === 'monolith' || type === 'bastion_monolith') return 'bastion_monolith';

    const genome = params.genome || {};
    const rawSpeciesId = params.speciesId || genome.speciesId || 'goblin';
    if (BLENDER_MODEL_MANIFEST[rawSpeciesId]) {
      return rawSpeciesId;
    }
    if (Array.isArray(genome.hybridParents) && genome.hybridParents.length > 0) {
      const parent0 = genome.hybridParents[0];
      if (BLENDER_MODEL_MANIFEST[parent0]) return parent0;
    }
    return 'goblin';
  }

  /**
   * Builds a lightweight synchronous hierarchical template for headless Node.js (`dry-run-sim.js`)
   * or pre-load fallback, containing the exact named Blender nodes.
   *
   * @param {string} modelKey
   * @returns {THREE.Group}
   */
  _createSyntheticTemplate(modelKey) {
    const root = new THREE.Group();
    root.name = `BlenderTemplate_${modelKey}`;

    const mat = new THREE.MeshStandardMaterial({
      color: 0x88ccff,
      roughness: 0.4,
      metalness: 0.3,
    });
    const body = new THREE.Mesh(new THREE.BoxGeometry(0.5, 0.7, 0.4), mat);
    body.name = 'Body';
    body.position.set(0, 0.95, 0);
    root.add(body);

    const head = new THREE.Mesh(new THREE.SphereGeometry(0.22, 8, 8), mat.clone());
    head.name = 'Head';
    head.position.set(0, 0.65, 0.08);
    body.add(head);

    const leftArm = new THREE.Mesh(new THREE.BoxGeometry(0.18, 0.5, 0.18), mat.clone());
    leftArm.name = 'LeftArm';
    leftArm.position.set(-0.38, 0.32, 0);
    body.add(leftArm);

    const rightArm = new THREE.Mesh(new THREE.BoxGeometry(0.18, 0.5, 0.18), mat.clone());
    rightArm.name = 'RightArm';
    rightArm.position.set(0.38, 0.32, 0);
    body.add(rightArm);

    const weapon = new THREE.Mesh(new THREE.BoxGeometry(0.08, 0.8, 0.08), mat.clone());
    weapon.name = 'Weapon';
    weapon.position.set(0, -0.4, 0.18);
    rightArm.add(weapon);

    if (modelKey === 'hero_guardian') {
      const heroBlade = new THREE.Mesh(new THREE.BoxGeometry(0.1, 1.3, 0.05), mat.clone());
      heroBlade.name = 'HeroBlade';
      weapon.add(heroBlade);

      const heroVisor = new THREE.Mesh(new THREE.BoxGeometry(0.3, 0.08, 0.06), mat.clone());
      heroVisor.name = 'HeroVisor';
      head.add(heroVisor);
    }

    if (modelKey === 'vulture' || modelKey === 'dragon') {
      const leftWing = new THREE.Mesh(new THREE.BoxGeometry(1.3, 0.06, 0.5), mat.clone());
      leftWing.name = 'LeftWing';
      leftWing.position.set(-0.28, 0.25, -0.06);
      body.add(leftWing);

      const rightWing = new THREE.Mesh(new THREE.BoxGeometry(1.3, 0.06, 0.5), mat.clone());
      rightWing.name = 'RightWing';
      rightWing.position.set(0.28, 0.25, -0.06);
      body.add(rightWing);
    }

    if (modelKey === 'shark') {
      const fl = new THREE.Mesh(new THREE.BoxGeometry(0.2, 0.6, 0.2), mat.clone());
      fl.name = 'AmphibiousLeg_FL';
      leftArm.add(fl);
      const fr = new THREE.Mesh(new THREE.BoxGeometry(0.2, 0.6, 0.2), mat.clone());
      fr.name = 'AmphibiousLeg_FR';
      rightArm.add(fr);
    }

    const tail = new THREE.Mesh(new THREE.BoxGeometry(0.16, 0.4, 0.16), mat.clone());
    tail.name = 'Tail';
    tail.position.set(0, 0.1, -0.25);
    body.add(tail);

    const leftLeg = new THREE.Mesh(new THREE.BoxGeometry(0.2, 0.6, 0.2), mat.clone());
    leftLeg.name = 'LeftLeg';
    leftLeg.position.set(-0.2, 0.6, 0);
    root.add(leftLeg);

    const rightLeg = new THREE.Mesh(new THREE.BoxGeometry(0.2, 0.6, 0.2), mat.clone());
    rightLeg.name = 'RightLeg';
    rightLeg.position.set(0.2, 0.6, 0);
    root.add(rightLeg);

    root.traverse((child) => {
      if (child.isMesh) {
        child.receiveShadow = false;
        child.castShadow = child.name === 'Body';
      }
    });

    return root;
  }

  /**
   * Preloads and caches all 14 `.glb` models from `/assets/models/*.glb`.
   * Safe to call in both browser and headless Node.js (`npm run dry-run`).
   *
   * @returns {Promise<{ loaded: number, total: number, headless: boolean }>}
   */
  preloadAll() {
    if (this._preloadPromise) {
      return this._preloadPromise;
    }

    const entries = Object.entries(BLENDER_MODEL_MANIFEST);
    const isBrowser = typeof window !== 'undefined' && typeof document !== 'undefined';

    if (!isBrowser) {
      // Headless Node.js mode (`npm run dry-run`): populate synthetic templates synchronously
      for (const [key] of entries) {
        if (!this.templates.has(key)) {
          this.templates.set(key, this._createSyntheticTemplate(key));
        }
      }
      this.loadedCount = this.templates.size;
      this.isLoaded = true;
      this._preloadPromise = Promise.resolve({
        loaded: this.loadedCount,
        total: entries.length,
        headless: true,
      });
      return this._preloadPromise;
    }

    if (!this._loader) {
      this._loader = new GLTFLoader();
    }

    logger.info('BLENDER_3D', `📦 Préchargement des ${entries.length} modèles 3D Blender (.glb)...`);

    const loadTasks = entries.map(
      ([key, url]) =>
        new Promise((resolve) => {
          this._loader.load(
            url,
            (gltf) => {
              const sceneRoot = gltf.scene || new THREE.Group();
              sceneRoot.name = `BlenderGLB_${key}`;
              sceneRoot.traverse((child) => {
                if (child.isMesh) {
                  child.receiveShadow = false;
                  child.castShadow = child.name === 'Body';
                }
              });
              this.templates.set(key, sceneRoot);
              this.loadedCount++;
              this._upgradePendingGroupsForKey(key);
              resolve({ key, ok: true });
            },
            undefined,
            (err) => {
              logger.warn('BLENDER_3D', `⚠️ Échec de chargement pour ${url}, utilisation du fallback`, err);
              const fallback = this._createSyntheticTemplate(key);
              this.templates.set(key, fallback);
              this._upgradePendingGroupsForKey(key);
              resolve({ key, ok: false });
            }
          );
        })
    );

    this._preloadPromise = Promise.all(loadTasks).then((results) => {
      this.isLoaded = true;
      const okCount = results.filter((r) => r.ok).length;
      logger.info(
        'BLENDER_3D',
        `✅ ${okCount}/${entries.length} modèles 3D Blender (.glb) chargés et actifs !`,
        { loaded: okCount, total: entries.length }
      );
      return { loaded: okCount, total: entries.length, headless: false };
    });

    return this._preloadPromise;
  }

  /**
   * Upgrades any already-created creature groups that were waiting for `modelKey` to finish loading.
   * @param {string} modelKey
   */
  _upgradePendingGroupsForKey(modelKey) {
    for (const group of this.registeredGroups) {
      if (!group || group.userData?.blenderModelKey !== modelKey) continue;
      if (group.userData?.blenderTemplateApplied) continue;
      this._populateBlenderModelRoot(group, group.userData.blenderSpecParams || {});
      this._applyModeVisibilityToGroup(group);
    }
  }

  /**
   * Decorates a creature/hero/NPC `THREE.Group` produced by `buildCreatureMesh(params)`
   * with a cloned `.glb` model (`group.userData.blenderModelRoot`), links its articulated
   * limb nodes (`Body`, `Head`, `LeftArm`, `RightArm`, `LeftLeg`, `RightLeg`, `LeftWing`,
   * `RightWing`, `Tail`, `Weapon`), applies genetic/elemental/role material tinting,
   * and toggles base procedural mesh visibility according to `blenderMode`.
   *
   * @param {THREE.Group} group - Root creature group created by `buildCreatureMesh`.
   * @param {Object} [params={}] - Creation parameters passed to `buildCreatureMesh`.
   * @returns {THREE.Group} The decorated `group`.
   */
  decorateCreatureGroup(group, params = {}) {
    if (!group) return group;
    group.userData = group.userData || {};

    const modelKey = this.getModelKeyForSpec(params);
    group.userData.blenderModelKey = modelKey;
    group.userData.blenderSpecParams = params;

    // 1. Collect procedural base meshes (excluding overlays, mutation crowns/bulbs/runes, auras, and role rings)
    if (!Array.isArray(group.userData.proceduralBaseMeshes)) {
      const limbs = group.userData.limbs || {};
      const protectedRoots = new Set(
        [
          limbs.overlayGroup,
          limbs.emberCrown,
          limbs.venomGroup,
          limbs.auraRing,
          limbs.titanRunes,
          group.userData.heroWeaponAura,
        ].filter(Boolean)
      );

      // Keep NPC ground role ring visible in both modes
      for (const child of group.children) {
        if (child.isMesh && child.geometry?.type === 'RingGeometry') {
          protectedRoots.add(child);
        }
      }

      const isInsideProtected = (obj) => {
        let curr = obj;
        while (curr && curr !== group) {
          if (protectedRoots.has(curr)) return true;
          curr = curr.parent;
        }
        return false;
      };

      const baseMeshes = [];
      group.traverse((child) => {
        if (child.isMesh && !isInsideProtected(child)) {
          baseMeshes.push(child);
        }
      });
      group.userData.proceduralBaseMeshes = baseMeshes;
    }

    // 2. Create `group.userData.blenderModelRoot` container
    let blenderModelRoot = group.userData.blenderModelRoot;
    if (!blenderModelRoot) {
      blenderModelRoot = new THREE.Group();
      blenderModelRoot.name = `BlenderModelRoot_${modelKey}`;
      group.add(blenderModelRoot);
      group.userData.blenderModelRoot = blenderModelRoot;
    }

    // 3. If headless and templates not yet initialized, initialize synthetic templates
    const isBrowser = typeof window !== 'undefined' && typeof document !== 'undefined';
    if (!isBrowser && !this.templates.has(modelKey)) {
      this.templates.set(modelKey, this._createSyntheticTemplate(modelKey));
    } else if (isBrowser && !this._preloadPromise) {
      // Trigger background preload if not started yet
      this.preloadAll();
    }

    // 4. Populate `blenderModelRoot` from template (or placeholder until async load completes)
    this._populateBlenderModelRoot(group, params);

    // 5. Register group and apply current mode visibility
    this.registeredGroups.add(group);
    this._applyModeVisibilityToGroup(group);

    return group;
  }

  /**
   * Decorates an Ancient Relic Monolith `THREE.Group` with `bastion_monolith.glb`.
   * @param {THREE.Group} group
   * @returns {THREE.Group}
   */
  decorateMonolithGroup(group) {
    return this.decorateCreatureGroup(group, { type: 'monolith' });
  }

  /**
   * Clones the cached `.glb` template into `group.userData.blenderModelRoot`, extracts
   * articulated limb nodes, and applies material tinting for roles, mutations, hybrids, and weapons.
   *
   * @param {THREE.Group} group
   * @param {Object} params
   */
  _populateBlenderModelRoot(group, params = {}) {
    const modelKey = group.userData.blenderModelKey || this.getModelKeyForSpec(params);
    const blenderModelRoot = group.userData.blenderModelRoot;
    if (!blenderModelRoot) return;

    while (blenderModelRoot.children.length > 0) {
      blenderModelRoot.remove(blenderModelRoot.children[0]);
    }

    const template = this.templates.get(modelKey);
    const hasRealTemplate = Boolean(template);
    const sourceRoot = template || this._createSyntheticTemplate(modelKey);
    const instance = sourceRoot.clone(true);

    // Apply sub-mesh shadow diet without cloning materials per entity instance
    instance.traverse((child) => {
      if (child.isMesh) {
        child.receiveShadow = false;
        child.castShadow = child.name === 'Body';
      }
    });

    blenderModelRoot.add(instance);
    group.userData.blenderTemplateApplied = hasRealTemplate;

    // Extract named articulated limb nodes
    const nodes = {};
    for (const nodeName of LIMB_NODE_NAMES) {
      const found = instance.getObjectByName(nodeName);
      if (found) {
        nodes[nodeName] = found;
      }
    }

    const bodyNode = nodes.Body || instance;
    const baseBodyY = bodyNode.position ? bodyNode.position.y : group.userData.limbs?.baseBodyY || 0.95;

    const blenderLimbs = {
      body: bodyNode,
      head: nodes.Head || null,
      leftArm: nodes.LeftArm || null,
      rightArm: nodes.RightArm || null,
      leftLeg: nodes.LeftLeg || null,
      rightLeg: nodes.RightLeg || null,
      leftWing: nodes.LeftWing || null,
      rightWing: nodes.RightWing || null,
      tail: nodes.Tail || null,
      weapon: nodes.Weapon || null,
      heroBlade: nodes.HeroBlade || null,
      heroVisor: nodes.HeroVisor || null,
      amphibiousLegFL: nodes.AmphibiousLeg_FL || null,
      amphibiousLegFR: nodes.AmphibiousLeg_FR || null,
      baseBodyY,
    };
    group.userData.blenderLimbs = blenderLimbs;

    // Apply entity-specific material hooks & genetic/role/elemental tinting
    const type = params.type || 'enemy';
    if (type === 'player' || type === 'hero') {
      this._bindHeroBlenderMaterials(group, instance, blenderLimbs);
    } else if (type === 'npc') {
      this._applyNpcRolePalette(instance, params.role || 'scout', modelKey);
    } else {
      this._applyCreatureGeneticsToBlenderInstance(group, instance, blenderLimbs, params);
    }
  }

  /**
   * Binds the Hero Guardian's `.glb` `HeroBlade` and `HeroVisor` materials so
   * equipping Elemental Greatswords dynamically recolors both the Blender `.glb`
   * sword/visor and the procedural fallback. Only clones `Mat_HeroBlade` and `Mat_HeroVisor`.
   *
   * @param {THREE.Group} group
   * @param {THREE.Object3D} instance
   * @param {Object} blenderLimbs
   */
  _bindHeroBlenderMaterials(group, instance, blenderLimbs) {
    let bladeMat = null;
    let visorMat = null;

    instance.traverse((child) => {
      if (!child.isMesh || !child.material) return;
      const replaceIfHeroMat = (m) => {
        if (!m) return m;
        if (m.name?.includes('Mat_HeroBlade') || child.name === 'HeroBlade') {
          if (!bladeMat) bladeMat = m.clone();
          return bladeMat;
        }
        if (m.name?.includes('Mat_HeroVisor') || child.name === 'HeroVisor') {
          if (!visorMat) visorMat = m.clone();
          return visorMat;
        }
        return m;
      };
      if (Array.isArray(child.material)) {
        child.material = child.material.map(replaceIfHeroMat);
      } else {
        child.material = replaceIfHeroMat(child.material);
      }
    });

    group.userData.blenderHeroBlade = blenderLimbs.heroBlade || blenderLimbs.weapon;
    group.userData.blenderHeroBladeMat = bladeMat;
    group.userData.blenderHeroVisorMat = visorMat;

    // Sync with current procedural blade color if an elemental weapon was already applied
    if (group.userData.heroBladeMat && bladeMat) {
      bladeMat.color.copy(group.userData.heroBladeMat.color);
      if (bladeMat.emissive && group.userData.heroBladeMat.emissive) {
        bladeMat.emissive.copy(group.userData.heroBladeMat.emissive);
        bladeMat.emissiveIntensity = group.userData.heroBladeMat.emissiveIntensity || 1.65;
      }
    }
  }

  /**
   * Updates the Hero Guardian's `.glb` greatsword blade and visor when equipping an Elemental Weapon.
   *
   * @param {THREE.Group} group
   * @param {Object} [weaponSpec={}]
   */
  applyHeroWeaponAppearance(group, weaponSpec = {}) {
    if (!group || !group.userData) return;
    const bladeColor = weaponSpec.bladeColorHex ?? weaponSpec.colorHex ?? 0x88eeff;
    const emissiveColor = weaponSpec.emissiveColorHex ?? weaponSpec.colorHex ?? 0x1e90ff;
    const emissiveIntensity = weaponSpec.emissiveIntensity ?? 1.85;
    const isElemental = Boolean(weaponSpec.id && weaponSpec.id !== 'runic_steel');

    const bladeMat = group.userData.blenderHeroBladeMat;
    if (bladeMat) {
      bladeMat.color.setHex(bladeColor);
      if (bladeMat.emissive) {
        bladeMat.emissive.setHex(emissiveColor);
        bladeMat.emissiveIntensity = emissiveIntensity;
      }
    }
    const visorMat = group.userData.blenderHeroVisorMat;
    if (visorMat) {
      visorMat.color.setHex(bladeColor);
      if (visorMat.emissive) {
        visorMat.emissive.setHex(emissiveColor);
      }
    }
    const bladeNode = group.userData.blenderHeroBlade;
    if (bladeNode) {
      const scaleW = isElemental ? 1.22 : 1.0;
      const scaleL = weaponSpec.id === 'ice_greatsword' ? 1.18 : isElemental ? 1.1 : 1.0;
      bladeNode.scale.set(scaleW, scaleL, scaleW);
    }
  }

  /**
   * Tints an allied NPC `.glb` clone according to its assigned role (`'scout' | 'guard' | 'harvester'`),
   * sharing tinted materials via `this.materialCache`.
   *
   * @param {THREE.Object3D} instance
   * @param {string} role
   * @param {string} [modelKey='npc_survivor']
   */
  _applyNpcRolePalette(instance, role = 'scout', modelKey = 'npc_survivor') {
    const rolePalette = {
      scout: { tunic: 0x16697a, cloak: 0x2ed573, accent: 0x48dbfb },
      guard: { tunic: 0x3b4d61, cloak: 0xe6a145, accent: 0xff6b6b },
      harvester: { tunic: 0x6b5335, cloak: 0x38c172, accent: 0xfeca57 },
    };
    const pal = rolePalette[role] || rolePalette.scout;
    const cacheKey = `${modelKey}|${role || 'scout'}|||`;
    let roleMatMap = this.materialCache.get(cacheKey);
    if (!roleMatMap) {
      roleMatMap = new Map();
      this.materialCache.set(cacheKey, roleMatMap);
    }

    const resolveRoleMat = (m) => {
      if (!m || !m.name) return m;
      const isTunic = m.name.includes('Mat_Tunic');
      const isCloak = m.name.includes('Mat_Cloak');
      const isAccent = m.name.includes('Mat_Accent');
      if (!isTunic && !isCloak && !isAccent) return m;

      let cached = roleMatMap.get(m);
      if (!cached) {
        cached = m.clone();
        if (isTunic) {
          cached.color.setHex(pal.tunic);
        } else if (isCloak) {
          cached.color.setHex(pal.cloak);
        } else if (isAccent) {
          cached.color.setHex(pal.accent);
          if (cached.emissive) {
            cached.emissive.setHex(pal.accent);
            cached.emissiveIntensity = role === 'scout' ? 1.6 : 0.7;
          }
        }
        roleMatMap.set(m, cached);
      }
      return cached;
    };

    instance.traverse((child) => {
      if (!child.isMesh || !child.material) return;
      if (Array.isArray(child.material)) {
        child.material = child.material.map(resolveRoleMat);
      } else {
        child.material = resolveRoleMat(child.material);
      }
    });
  }

  /**
   * Applies hybrid color blending, Mendelian mutation emissive tints (`pyro_gland`, `cryo_blood`,
   * `venom_sacs`, `vampiric_maw`), and Shark amphibious leg bindings onto an enemy `.glb` clone.
   * Reuses the template's original materials directly when non-hybrid with no tinting mutations,
   * and caches tinted material maps in `this.materialCache` otherwise.
   *
   * @param {THREE.Group} group
   * @param {THREE.Object3D} instance
   * @param {Object} blenderLimbs
   * @param {Object} params
   */
  _applyCreatureGeneticsToBlenderInstance(group, instance, blenderLimbs, params = {}) {
    const genome = params.genome || {};
    const modelKey = group.userData.blenderModelKey || 'goblin';
    const primaryId = modelKey;
    const isHybrid = Boolean(genome.isHybrid);
    const hybridParents =
      Array.isArray(genome.hybridParents) && genome.hybridParents.length >= 2
        ? genome.hybridParents
        : [primaryId, primaryId];
    const secondaryId = isHybrid ? hybridParents[1] || primaryId : primaryId;

    const spA = CONFIG.SPECIES?.[primaryId] || SPECIES_FALLBACK_COLORS[primaryId] || SPECIES_FALLBACK_COLORS.goblin;
    const spB = CONFIG.SPECIES?.[secondaryId] || SPECIES_FALLBACK_COLORS[secondaryId] || spA;

    const mutationIds = getMutationIds(genome);
    const hasMut = (id) => mutationIds.includes(id);

    const skinColor = toColor(spA.color, 0x5c8a3c);
    const accentColor = toColor(spA.accentColor, 0x9ab858);
    if (isHybrid && secondaryId !== primaryId) {
      skinColor.lerp(toColor(spB.color, 0x626a73), 0.45);
      accentColor.lerp(toColor(spB.accentColor, 0x9aa4b0), 0.5);
    }

    let emissiveColor = null;
    let emissiveIntensity = 0;
    if (hasMut('pyro_gland')) {
      skinColor.lerp(new THREE.Color(0x521808), 0.42);
      accentColor.setHex(0xff5500);
      emissiveColor = new THREE.Color(0xff3b00);
      emissiveIntensity = 0.55;
    } else if (hasMut('cryo_blood')) {
      skinColor.lerp(new THREE.Color(0x1f6f8b), 0.4);
      emissiveColor = new THREE.Color(0x00b4d8);
      emissiveIntensity = 0.38;
    } else if (hasMut('venom_sacs')) {
      emissiveColor = new THREE.Color(0x1b7a1b);
      emissiveIntensity = 0.3;
    } else if (hasMut('vampiric_maw')) {
      skinColor.lerp(new THREE.Color(0x3a0ca3), 0.25);
      emissiveColor = new THREE.Color(0x800f2f);
      emissiveIntensity = 0.32;
    }

    if ((isHybrid && secondaryId !== primaryId) || emissiveColor) {
      const cacheKey = `${modelKey}|${params.role || ''}|${primaryId}|${secondaryId}|${mutationIds.join(',')}`;
      let tintedMatMap = this.materialCache.get(cacheKey);
      if (!tintedMatMap) {
        tintedMatMap = new Map();
        this.materialCache.set(cacheKey, tintedMatMap);
      }

      const resolveGeneticMat = (m) => {
        if (!m || !m.name) return m;
        const isSkin = m.name.includes('Mat_Skin');
        const isAccent = m.name.includes('Mat_Accent');
        if (!isSkin && !isAccent) return m;

        let cached = tintedMatMap.get(m);
        if (!cached) {
          cached = m.clone();
          if (isSkin) {
            cached.color.copy(skinColor);
            if (emissiveColor && cached.emissive) {
              cached.emissive.copy(emissiveColor);
              cached.emissiveIntensity = emissiveIntensity;
            }
          } else if (isAccent) {
            cached.color.copy(accentColor);
          }
          tintedMatMap.set(m, cached);
        }
        return cached;
      };

      instance.traverse((child) => {
        if (!child.isMesh || !child.material) return;
        if (Array.isArray(child.material)) {
          child.material = child.material.map(resolveGeneticMat);
        } else {
          child.material = resolveGeneticMat(child.material);
        }
      });
    }

    // Bind Shark amphibious legs on the Blender `.glb` instance so `setSharkAmphibiousMode` toggles them too
    if (primaryId === 'shark') {
      const bLegParts = [
        blenderLimbs.amphibiousLegFL,
        blenderLimbs.amphibiousLegFR,
        blenderLimbs.leftLeg,
        blenderLimbs.rightLeg,
      ].filter(Boolean);
      group.userData.blenderSharkLegParts = bLegParts;
      if (Array.isArray(group.userData.sharkLegParts)) {
        for (const p of bLegParts) {
          if (!group.userData.sharkLegParts.includes(p)) {
            group.userData.sharkLegParts.push(p);
          }
        }
      }
      const hasLandLegs =
        group.userData.amphibiousLegs !== undefined
          ? Boolean(group.userData.amphibiousLegs.visible)
          : true;
      for (const p of bLegParts) {
        p.visible = hasLandLegs;
      }
      if (blenderLimbs.body) {
        blenderLimbs.baseBodyY = hasLandLegs ? 0.86 : 0.38;
        blenderLimbs.body.position.y = blenderLimbs.baseBodyY;
      }
    }
  }

  /**
   * Applies visibility between `group.userData.blenderModelRoot` and `group.userData.proceduralBaseMeshes`
   * according to `this.blenderMode`.
   *
   * @param {THREE.Group} group
   */
  _applyModeVisibilityToGroup(group) {
    if (!group || !group.userData) return;
    const useBlender = Boolean(this.blenderMode && group.userData.blenderModelRoot);

    if (group.userData.blenderModelRoot) {
      group.userData.blenderModelRoot.visible = useBlender;
    }

    if (Array.isArray(group.userData.proceduralBaseMeshes)) {
      const isShark = group.userData.blenderModelKey === 'shark';
      const sharkLegsVisible =
        isShark && group.userData.amphibiousLegs
          ? Boolean(group.userData.amphibiousLegs.visible)
          : true;
      const sharkLegSet = isShark && Array.isArray(group.userData.sharkLegParts)
        ? new Set(group.userData.sharkLegParts)
        : null;

      for (const mesh of group.userData.proceduralBaseMeshes) {
        if (!mesh) continue;
        if (useBlender) {
          mesh.visible = false;
        } else if (sharkLegSet && (sharkLegSet.has(mesh) || sharkLegSet.has(mesh.parent))) {
          mesh.visible = sharkLegsVisible;
        } else {
          mesh.visible = true;
        }
      }
    }
  }

  /**
   * Animates the articulated limb nodes (`Body`, `Head`, `LeftArm`, `RightArm`, `LeftLeg`,
   * `RightLeg`, `LeftWing`, `RightWing`, `Tail`, `Weapon`) of a group's Blender `.glb` model.
   *
   * @param {THREE.Group} group - Root creature group.
   * @param {Object} [animState={}] - Current animation state (`{ isMoving, speed, isAttacking, attackProgress, hitFlash }`).
   * @param {number} [elapsedTime=0] - Elapsed game time in seconds.
   * @param {number} [dt=0.016] - Frame delta time in seconds.
   */
  animateBlenderModel(group, animState = {}, elapsedTime = 0, dt = 0.016) {
    const bLimbs = group?.userData?.blenderLimbs;
    if (!bLimbs) return;

    const pLimbs = group.userData?.limbs || {};
    const isMoving = Boolean(animState.isMoving || (animState.speed && animState.speed > 0.25));
    const moveSpeed = animState.speed || 4.5;
    const phase = elapsedTime * Math.max(4.5, moveSpeed * 1.15) + (group.id || 0) * 0.7;
    const isHovering = Boolean(pLimbs.isHovering);
    const isQuadruped = Boolean(pLimbs.isQuadruped);
    const isHopper = Boolean(pLimbs.isHopper);

    // Sync Shark amphibious leg height if applicable
    if (group.userData?.blenderModelKey === 'shark' && group.userData?.amphibiousLegs) {
      const legsVis = Boolean(group.userData.amphibiousLegs.visible);
      bLimbs.baseBodyY = legsVis ? 0.86 : 0.38;
      if (Array.isArray(group.userData.blenderSharkLegParts)) {
        for (const part of group.userData.blenderSharkLegParts) {
          if (part) part.visible = legsVis;
        }
      }
    }

    // 1. Body vertical bob / hover oscillation
    if (bLimbs.body) {
      const hoverOffset = isHovering ? Math.sin(elapsedTime * 3.8 + (group.id || 0)) * 0.22 : 0;
      const hopAmp = isHopper ? 0.22 : 0.1;
      const walkBob =
        isMoving && !isHovering
          ? Math.abs(Math.sin(phase)) * hopAmp
          : Math.sin(elapsedTime * 2.2) * 0.03;
      bLimbs.body.position.y = bLimbs.baseBodyY + hoverOffset + walkBob;
    }

    // 2. Walk / Run Limb Stride
    if (isMoving && !isHovering) {
      const swingAmp = isQuadruped ? 0.52 : 0.6;
      if (bLimbs.leftLeg) bLimbs.leftLeg.rotation.x = Math.sin(phase) * swingAmp;
      if (bLimbs.rightLeg) bLimbs.rightLeg.rotation.x = -Math.sin(phase) * swingAmp;

      if (isQuadruped) {
        if (bLimbs.leftArm) bLimbs.leftArm.rotation.x = -Math.sin(phase) * swingAmp;
        if (bLimbs.rightArm) bLimbs.rightArm.rotation.x = Math.sin(phase) * swingAmp;
      } else {
        if (bLimbs.leftArm) bLimbs.leftArm.rotation.x = -Math.sin(phase) * (swingAmp * 0.75);
        if (bLimbs.rightArm && !animState.isAttacking) {
          bLimbs.rightArm.rotation.x = Math.sin(phase) * (swingAmp * 0.75);
        }
      }
    } else {
      const damp = Math.min(1, dt * 10);
      if (bLimbs.leftLeg) bLimbs.leftLeg.rotation.x *= 1 - damp;
      if (bLimbs.rightLeg) bLimbs.rightLeg.rotation.x *= 1 - damp;
      if (bLimbs.leftArm) bLimbs.leftArm.rotation.x *= 1 - damp;
      if (bLimbs.rightArm && !animState.isAttacking) bLimbs.rightArm.rotation.x *= 1 - damp;
    }

    // 3. Melee Attack Swing
    if (bLimbs.rightArm && (animState.isAttacking || animState.attackProgress > 0)) {
      const p =
        animState.attackProgress !== undefined
          ? animState.attackProgress
          : (Math.sin(elapsedTime * 16) + 1) * 0.5;
      bLimbs.rightArm.rotation.x = -Math.PI * 0.75 + Math.sin(p * Math.PI) * 1.85;
      bLimbs.rightArm.rotation.z = -Math.sin(p * Math.PI) * 0.35;
    } else if (bLimbs.rightArm) {
      bLimbs.rightArm.rotation.z *= 0.85;
    }

    // 4. Wing Flap (`LeftWing` / `RightWing`)
    if (bLimbs.leftWing && bLimbs.rightWing) {
      const flapFreq = isHovering || isMoving ? 7.5 : 3.2;
      const flapAmp = isHovering || isMoving ? 0.52 : 0.24;
      const flapAngle = Math.sin(elapsedTime * flapFreq + (group.id || 0)) * flapAmp;
      bLimbs.leftWing.rotation.z = flapAngle;
      bLimbs.rightWing.rotation.z = -flapAngle;
    }

    // 5. Tail / Cape Sway & Subtle Head Look
    if (bLimbs.tail) {
      bLimbs.tail.rotation.y = Math.sin(elapsedTime * (isMoving ? 6.0 : 2.2)) * 0.24;
    }
    if (bLimbs.head) {
      bLimbs.head.rotation.y = Math.sin(elapsedTime * 1.7 + (group.id || 0)) * 0.08;
    }

    // 6. Hit Flash Recoil
    if (bLimbs.body && typeof animState.hitFlash === 'number' && animState.hitFlash > 0) {
      bLimbs.body.rotation.z =
        Math.sin(animState.hitFlash * Math.PI * 4) * 0.16 * animState.hitFlash;
    } else if (bLimbs.body) {
      bLimbs.body.rotation.z *= 0.8;
    }
  }
}

/** Singleton BlenderModelManager instance used across Genesis Bastion. */
export const blenderModelManager = new BlenderModelManager();
export default blenderModelManager;
