/**
 * @file src/config.js
 * @description Centralized configuration module for Genesis Bastion.
 * Defines all world generation parameters, Conway's Game of Life ecological density
 * thresholds, base species traits across 3 evolutionary clades, the 7x7 symmetric
 * phylogenetic distance matrix governing inter-species hybridization, Mendelian
 * dominant mutations (including the iconic "Glande Pyroclastique / Feu" for the
 * Fire Troll scenario), Bastion defenses, Scout NPC parameters, and roguelike
 * player upgrades.
 */

export const CONFIG = {
  /**
   * 3D Island World & Spatial Grid Configuration
   */
  WORLD: {
    SIZE: 240,
    WATER_LEVEL: -1.2,
    BIOME_SCALE: 0.015,
    GRID_CELLS: 24,
    SAFE_SPAWN_RADIUS: 42,
    DAY_DURATION: 120,
  },

  /**
   * Conway's Game of Life & Darwinian Ecosystem Parameters
   */
  ECO: {
    TICK_INTERVAL: 12,
    MATURATION_TIME: 20,
    BABY_SCALE: 0.5,
    BABY_STAT_MULT: 0.55,
    BABY_METABOLISM_MULT: 0.5,
    MIN_DENSITY: 2,
    MAX_DENSITY: 6,
    OPTIMAL_MAX: 5,
    BASE_BIOMASS: 100,
    BIOMASS_REGEN: 18,
    BIRTH_BIOMASS_COST: 22,
    NEIGHBOR_RADIUS: 22,
    MUTATION_RATE: 0.08,
    DOMINANT_INHERITANCE_SINGLE: 0.78,
    DOMINANT_INHERITANCE_BOTH: 0.92,
    HYBRID_MAX_DIST: 0.45,
    HYBRID_BASE_CHANCE: 0.22,
    STARVATION_DPS: 4.5,
    INITIAL_POPULATION: 42,
    MAX_WORLD_POPULATION: 130,
    REPOPULATION_MIN_THRESHOLD: 2,
    SPECIES_WRATH_DURATION: 90,
    SHARK_LANDING_TIME_SEC: 40,
    SHARK_WAVE_INTERVAL_SEC: 35,
    MOLE_ERUPTION_TIME_SEC: 65,
    MOLE_WAVE_INTERVAL_SEC: 42,
    HERBIVORE_BIOMASS_ENRICHMENT: 6,
    PREY_REINTRODUCE_BIOMASS_COST: 25,
    INITIAL_FOOD: 60,
    MAX_FOOD: 150,
    FOOD_DECAY_PER_SEC: 1.2,
    WELL_FED_THRESHOLD: 25,
  },

  /**
   * Evolutionary Clade Metadata
   */
  CLADES: {
    greenskin: {
      id: 'greenskin',
      name: 'Peaux-Vertes',
      description: 'Tribu humanoïde robuste à forte adaptabilité territoriale (Gobelin, Orc, Troll).',
      color: '#4caf50',
      colorHex: 0x4caf50,
    },
    beast: {
      id: 'beast',
      name: 'Bêtes Sauvages',
      description: 'Prédateurs véloces de meute et des cieux (Loup, Lion, Vautour).',
      color: '#d99b38',
      colorHex: 0xd99b38,
    },
    apex: {
      id: 'apex',
      name: 'Prédateurs Apex',
      description: 'Créatures draconiques anciennes situées au sommet de la chaîne trophique (Dragon).',
      color: '#e04038',
      colorHex: 0xe04038,
    },
    abyssal: {
      id: 'abyssal',
      name: 'Émergents des Abysses & Profondeurs',
      description:
        'Espèces invasives surgissant progressivement de l’océan (Requin Marcheur Amphibie) et des galeries souterraines (Taupe Géante Fouisseuse).',
      color: '#2e86de',
      colorHex: 0x2e86de,
    },
    herbivore: {
      id: 'herbivore',
      name: 'Faune Herbivore (Gibier)',
      description:
        'Proies paisibles (Biche Sylvestre, Lapin des Plaines) qui enrichissent la biomasse, nourrissent les prédateurs et fournissent des Rations. Ne réapparaissent pas gratuitement si exterminées par vos sorts !',
      color: '#a3cb38',
      colorHex: 0xa3cb38,
    },
  },

  /**
   * Base Species Definitions (11 core species across 5 clades)
   */
  SPECIES: {
    goblin: {
      id: 'goblin',
      name: 'Gobelin',
      clade: 'greenskin',
      baseHp: 48,
      baseSpeed: 8.8,
      baseDamage: 8,
      baseSize: 0.78,
      baseGestationTime: 9,
      baseMaturationTime: 12,
      baseAggressiveness: 0.75,
      aggroStance: 'hostile',
      autoRepopulate: true,
      repopulationCooldown: 8,
      repopulationHabitatLabel: 'les terriers forestiers',
      repopulationMessageFR: 'Des Gobelins sauvages émergent de leurs terriers forestiers !',
      color: '#5b9e3e',
      accentColor: '#9be061',
      colorHex: 0x5b9e3e,
      accentHex: 0x9be061,
      preferredBiome: 'forest',
      metabolism: 3.2,
      fertility: 1.25,
      aggroRadius: 16,
      xpReward: 15,
      description: 'Éclaireur peau-verte agile, prolifique mais fragile en duel.',
    },
    orc: {
      id: 'orc',
      name: 'Orc',
      clade: 'greenskin',
      baseHp: 95,
      baseSpeed: 6.8,
      baseDamage: 15,
      baseSize: 1.08,
      baseGestationTime: 18,
      baseMaturationTime: 22,
      baseAggressiveness: 0.88,
      aggroStance: 'hostile',
      autoRepopulate: true,
      repopulationCooldown: 16,
      repopulationHabitatLabel: 'les campements enfouis des plaines',
      repopulationMessageFR: 'Une patrouille d’Orcs sauvages surgit des campements enfouis !',
      color: '#3f7833',
      accentColor: '#c97a3e',
      colorHex: 0x3f7833,
      accentHex: 0xc97a3e,
      preferredBiome: 'plains',
      metabolism: 4.8,
      fertility: 1.05,
      aggroRadius: 19,
      xpReward: 28,
      description: 'Guerrier tribal discipliné capable de s’hybrider avec les Gobelins et les Trolls.',
    },
    troll: {
      id: 'troll',
      name: 'Troll',
      clade: 'greenskin',
      baseHp: 175,
      baseSpeed: 5.1,
      baseDamage: 24,
      baseSize: 1.52,
      baseGestationTime: 30,
      baseMaturationTime: 34,
      baseAggressiveness: 0.48,
      aggroStance: 'territorial',
      autoRepopulate: true,
      repopulationCooldown: 16,
      repopulationHabitatLabel: 'les cavernes profondes des hautes terres',
      repopulationMessageFR: 'Des Trolls anciens sortent des cavernes profondes des hautes terres !',
      color: '#346357',
      accentColor: '#78a898',
      colorHex: 0x346357,
      accentHex: 0x78a898,
      preferredBiome: 'highlands',
      metabolism: 7.2,
      fertility: 0.85,
      aggroRadius: 21,
      xpReward: 48,
      description: 'Colosse massif des hautes terres. Redoutable s’il développe la Glande Pyroclastique.',
    },
    wolf: {
      id: 'wolf',
      name: 'Loup',
      clade: 'beast',
      baseHp: 58,
      baseSpeed: 9.6,
      baseDamage: 11,
      baseSize: 0.85,
      baseGestationTime: 13,
      baseMaturationTime: 15,
      baseAggressiveness: 0.82,
      aggroStance: 'hostile',
      autoRepopulate: true,
      repopulationCooldown: 12,
      repopulationHabitatLabel: 'les tanières sylvestres',
      repopulationMessageFR: 'Des Loups sauvages quittent leurs tanières sylvestres !',
      color: '#737d8c',
      accentColor: '#b8c4d4',
      colorHex: 0x737d8c,
      accentHex: 0xb8c4d4,
      preferredBiome: 'forest',
      metabolism: 3.8,
      fertility: 1.2,
      aggroRadius: 20,
      xpReward: 20,
      description: 'Chasseur de meute rapide qui prospère dans les forêts denses.',
    },
    lion: {
      id: 'lion',
      name: 'Lion',
      clade: 'beast',
      baseHp: 110,
      baseSpeed: 8.2,
      baseDamage: 18,
      baseSize: 1.15,
      baseGestationTime: 24,
      baseMaturationTime: 26,
      baseAggressiveness: 0.70,
      aggroStance: 'hostile',
      autoRepopulate: true,
      repopulationCooldown: 16,
      repopulationHabitatLabel: 'les hautes herbes sauvages',
      repopulationMessageFR: 'Un couple de Lions sauvages regagne son territoire dans les plaines !',
      color: '#d4943a',
      accentColor: '#7a4419',
      colorHex: 0xd4943a,
      accentHex: 0x7a4419,
      preferredBiome: 'plains',
      metabolism: 5.4,
      fertility: 1.0,
      aggroRadius: 22,
      xpReward: 34,
      description: 'Félin territorial dominant des plaines dorées.',
    },
    vulture: {
      id: 'vulture',
      name: 'Vautour',
      clade: 'beast',
      baseHp: 64,
      baseSpeed: 10.2,
      baseDamage: 13,
      baseSize: 0.9,
      baseGestationTime: 15,
      baseMaturationTime: 17,
      baseAggressiveness: 0.38,
      aggroStance: 'territorial',
      autoRepopulate: true,
      repopulationCooldown: 12,
      repopulationHabitatLabel: 'les nids des falaises escarpées',
      repopulationMessageFR: 'Des Vautours descendent en piqué depuis les nids des falaises !',
      color: '#5e4b44',
      accentColor: '#d96b52',
      colorHex: 0x5e4b44,
      accentHex: 0xd96b52,
      preferredBiome: 'highlands',
      metabolism: 3.5,
      fertility: 1.1,
      aggroRadius: 24,
      xpReward: 24,
      description: 'Charognard ailé des crêtes rocheuses, chaînon évolutif vers les reptiles ailés.',
    },
    dragon: {
      id: 'dragon',
      name: 'Dragon',
      clade: 'apex',
      baseHp: 680,
      baseSpeed: 8.2,
      baseDamage: 58,
      baseSize: 2.05,
      baseGestationTime: 65,
      baseMaturationTime: 50,
      baseAggressiveness: 0.08,
      aggroStance: 'pacifist_apex',
      autoRepopulate: true,
      repopulationCooldown: 28,
      repopulationHabitatLabel: 'les crêtes volcaniques inaccessibles',
      repopulationMessageFR: 'Un couple de Dragons ancestraux se pose sur la caldeira volcanique !',
      color: '#b82929',
      accentColor: '#ff9436',
      colorHex: 0xb82929,
      accentHex: 0xff9436,
      preferredBiome: 'volcanic',
      metabolism: 10.5,
      fertility: 0.65,
      aggroRadius: 26,
      xpReward: 180,
      description: 'Souverain draconique paisible de la caldeira volcanique. N’attaque jamais le premier, mais déclenche le Courroux Draconique de toute son espèce s’il est provoqué.',
    },
    shark: {
      id: 'shark',
      name: 'Requin Marcheur',
      clade: 'abyssal',
      baseHp: 135,
      baseSpeed: 7.8,
      baseDamage: 22,
      baseSize: 1.32,
      baseGestationTime: 22,
      baseMaturationTime: 24,
      baseAggressiveness: 0.86,
      aggroStance: 'hostile',
      isAquaticInitially: true,
      emergenceType: 'ocean_beach',
      emergenceTimeSec: 40,
      autoRepopulate: true,
      repopulationCooldown: 20,
      repopulationHabitatLabel: 'les récifs abyssaux du large',
      repopulationMessageFR: 'Un banc de Requins Marcheurs débarque des récifs abyssaux sur la plage !',
      color: '#2b5876',
      accentColor: '#74b9ff',
      colorHex: 0x2b5876,
      accentHex: 0x74b9ff,
      preferredBiome: 'beach',
      metabolism: 6.2,
      fertility: 0.95,
      aggroRadius: 23,
      xpReward: 42,
      description: 'Prédateur océanique qui nage autour de l’île avant de développer des pattes amphibies musclées pour débarquer sur les plages et traquer les survivants.',
    },
    giant_mole: {
      id: 'giant_mole',
      name: 'Taupe Géante',
      clade: 'abyssal',
      baseHp: 150,
      baseSpeed: 6.4,
      baseDamage: 21,
      baseSize: 1.25,
      baseGestationTime: 20,
      baseMaturationTime: 22,
      baseAggressiveness: 0.76,
      aggroStance: 'hostile',
      isSubterraneanInitially: true,
      emergenceType: 'subterranean',
      emergenceTimeSec: 65,
      autoRepopulate: true,
      repopulationCooldown: 18,
      repopulationHabitatLabel: 'les galeries souterraines profondes',
      repopulationMessageFR: 'Des Taupes Géantes Fouisseuses jaillissent des galeries souterraines !',
      color: '#5c4033',
      accentColor: '#ff85a2',
      colorHex: 0x5c4033,
      accentHex: 0xff85a2,
      preferredBiome: 'highlands',
      metabolism: 5.8,
      fertility: 1.0,
      aggroRadius: 20,
      xpReward: 38,
      description: 'Fouisseur aveugle aux griffes métalliques qui surgit des profondeurs souterraines en projetant des geysers de roche.',
    },
    rabbit: {
      id: 'rabbit',
      name: 'Lapin des Plaines',
      clade: 'herbivore',
      baseHp: 26,
      baseSpeed: 9.8,
      baseDamage: 0,
      baseSize: 0.58,
      baseGestationTime: 7.5,
      baseMaturationTime: 9.5,
      baseAggressiveness: 0.0,
      aggroStance: 'prey_pacifist',
      isHerbivorePrey: true,
      foodYield: 18,
      healYield: 12,
      biomassEnrichmentPerTick: 6,
      fleeRadius: 11,
      autoRepopulate: false,
      repopulationCooldown: 0,
      repopulationHabitatLabel: 'les prairies fleuries (Réintroduction manuelle requise si éteint)',
      repopulationMessageFR: 'Des Lapins des Plaines ont été réintroduits dans les prairies !',
      color: '#dcdde1',
      accentColor: '#fbc531',
      colorHex: 0xdcdde1,
      accentHex: 0xfbc531,
      preferredBiome: 'plains',
      metabolism: 1.4,
      fertility: 1.45,
      aggroRadius: 12,
      xpReward: 8,
      description: 'Petit herbivore véloce qui enrichit la biomasse et fournit +18 Rations. Attention : ne réapparaît pas gratuitement si vos sorts de zone exterminent le troupeau !',
    },
    deer: {
      id: 'deer',
      name: 'Biche Sylvestre',
      clade: 'herbivore',
      baseHp: 54,
      baseSpeed: 10.5,
      baseDamage: 0,
      baseSize: 1.05,
      baseGestationTime: 15,
      baseMaturationTime: 17,
      baseAggressiveness: 0.0,
      aggroStance: 'prey_pacifist',
      isHerbivorePrey: true,
      foodYield: 35,
      healYield: 25,
      biomassEnrichmentPerTick: 8,
      fleeRadius: 11,
      autoRepopulate: false,
      repopulationCooldown: 0,
      repopulationHabitatLabel: 'les clairières sylvestres (Réintroduction manuelle requise si éteint)',
      repopulationMessageFR: 'Une harde de Biches Sylvestres a été réintroduite dans la forêt !',
      color: '#c27d38',
      accentColor: '#f5f6fa',
      colorHex: 0xc27d38,
      accentHex: 0xf5f6fa,
      preferredBiome: 'forest',
      metabolism: 2.2,
      fertility: 1.15,
      aggroRadius: 14,
      xpReward: 14,
      description: 'Herbivore gracieux des clairières qui nourrit la faune carnivore et donne +35 Rations. Veillez à ne pas décimer la harde avec vos sorts dévastateurs !',
    },
  },

  /**
   * 2D Symmetric Phylogenetic Distance Matrix between all 11 species.
   * Pairs with distance <= ECO.HYBRID_MAX_DIST (0.45) can interbreed to produce fertile hybrids.
   * Distant species (> 0.45, e.g. goblin-dragon = 0.85, herbivores vs carnivores >= 0.88) are reproductively isolated.
   */
  PHYLOGENY_DIST: {
    goblin: {
      goblin: 0.0,
      orc: 0.18,
      troll: 0.32,
      wolf: 0.62,
      lion: 0.72,
      vulture: 0.78,
      dragon: 0.85,
      shark: 0.76,
      giant_mole: 0.58,
      rabbit: 0.92,
      deer: 0.94,
    },
    orc: {
      goblin: 0.18,
      orc: 0.0,
      troll: 0.22,
      wolf: 0.44,
      lion: 0.58,
      vulture: 0.70,
      dragon: 0.68,
      shark: 0.52,
      giant_mole: 0.38,
      rabbit: 0.92,
      deer: 0.90,
    },
    troll: {
      goblin: 0.32,
      orc: 0.22,
      troll: 0.0,
      wolf: 0.64,
      lion: 0.60,
      vulture: 0.66,
      dragon: 0.42,
      shark: 0.42,
      giant_mole: 0.32,
      rabbit: 0.95,
      deer: 0.92,
    },
    wolf: {
      goblin: 0.62,
      orc: 0.44,
      troll: 0.64,
      wolf: 0.0,
      lion: 0.20,
      vulture: 0.40,
      dragon: 0.74,
      shark: 0.34,
      giant_mole: 0.44,
      rabbit: 0.88,
      deer: 0.88,
    },
    lion: {
      goblin: 0.72,
      orc: 0.58,
      troll: 0.60,
      wolf: 0.20,
      lion: 0.0,
      vulture: 0.35,
      dragon: 0.62,
      shark: 0.44,
      giant_mole: 0.42,
      rabbit: 0.90,
      deer: 0.88,
    },
    vulture: {
      goblin: 0.78,
      orc: 0.70,
      troll: 0.66,
      wolf: 0.40,
      lion: 0.35,
      vulture: 0.0,
      dragon: 0.38,
      shark: 0.62,
      giant_mole: 0.68,
      rabbit: 0.90,
      deer: 0.90,
    },
    dragon: {
      goblin: 0.85,
      orc: 0.68,
      troll: 0.42,
      wolf: 0.74,
      lion: 0.62,
      vulture: 0.38,
      dragon: 0.0,
      shark: 0.40,
      giant_mole: 0.64,
      rabbit: 0.96,
      deer: 0.95,
    },
    shark: {
      goblin: 0.76,
      orc: 0.52,
      troll: 0.42,
      wolf: 0.34,
      lion: 0.44,
      vulture: 0.62,
      dragon: 0.40,
      shark: 0.0,
      giant_mole: 0.48,
      rabbit: 0.94,
      deer: 0.94,
    },
    giant_mole: {
      goblin: 0.58,
      orc: 0.38,
      troll: 0.32,
      wolf: 0.44,
      lion: 0.42,
      vulture: 0.68,
      dragon: 0.64,
      shark: 0.48,
      giant_mole: 0.0,
      rabbit: 0.86,
      deer: 0.88,
    },
    rabbit: {
      goblin: 0.92,
      orc: 0.92,
      troll: 0.95,
      wolf: 0.88,
      lion: 0.90,
      vulture: 0.90,
      dragon: 0.96,
      shark: 0.94,
      giant_mole: 0.86,
      rabbit: 0.0,
      deer: 0.28,
    },
    deer: {
      goblin: 0.94,
      orc: 0.90,
      troll: 0.92,
      wolf: 0.88,
      lion: 0.88,
      vulture: 0.90,
      dragon: 0.95,
      shark: 0.94,
      giant_mole: 0.88,
      rabbit: 0.28,
      deer: 0.0,
    },
  },

  /**
   * Mendelian Dominant Mutations Catalog.
   * When a mutation emerges spontaneously (de novo) or is carried by a parent,
   * its fitnessBonus increases mate selection weight and it inherits dominantly (78%–92%),
   * swiftly sweeping through the population unless the Player hunts down Patient Zero.
   */
  MUTATIONS: {
    pyro_gland: {
      id: 'pyro_gland',
      name: 'Glande Pyroclastique (Feu)',
      shortLabel: 'Pyro / Feu',
      description:
        'Organe exocrine incandescent générant une couronne de magma et des attaques enflammées dévastatrices. Rend les Trolls de Feu capables de dominer tout un biome.',
      dominant: true,
      fitnessBonus: 0.45,
      metabolismCost: 1.15,
      statMultipliers: {
        maxHp: 1.25,
        strength: 1.45,
        speed: 1.08,
        size: 1.18,
      },
      colorHex: 0xff4500,
      emissiveHex: 0xff2200,
      colorCss: '#ff4500',
      emissiveCss: '#ff2200',
      visualTag: 'pyro_crown',
    },
    venom_sacs: {
      id: 'venom_sacs',
      name: 'Sacs à Venin Neurotoxique',
      shortLabel: 'Venin',
      description:
        'Bulbes dorsaux bioluminescents sécrétant des toxines corrosives qui augmentent la létalité et l’agressivité.',
      dominant: true,
      fitnessBonus: 0.34,
      metabolismCost: 1.05,
      statMultipliers: {
        maxHp: 1.05,
        strength: 1.35,
        speed: 1.15,
        size: 1.04,
      },
      colorHex: 0x39ff14,
      emissiveHex: 0x1ec800,
      colorCss: '#39ff14',
      emissiveCss: '#1ec800',
      visualTag: 'venom_bulbs',
    },
    osteo_plating: {
      id: 'osteo_plating',
      name: 'Carapace Ostéo-Dermique',
      shortLabel: 'Carapace',
      description:
        'Plaques osseuses d’ivoire soudées sur le thorax et les épaules, conférant une résistance massive aux coups.',
      dominant: true,
      fitnessBonus: 0.38,
      metabolismCost: 1.1,
      statMultipliers: {
        maxHp: 1.55,
        strength: 1.12,
        speed: 0.94,
        size: 1.16,
      },
      colorHex: 0xe8e4d9,
      emissiveHex: 0x9e9578,
      colorCss: '#e8e4d9',
      emissiveCss: '#9e9578',
      visualTag: 'bone_armor',
    },
    vampiric_maw: {
      id: 'vampiric_maw',
      name: 'Crocs Hématophages',
      shortLabel: 'Vampirique',
      description:
        'Mandibules écarlates qui régénèrent la créature en combat et stimulent sa fécondité prédatrice.',
      dominant: true,
      fitnessBonus: 0.4,
      metabolismCost: 1.08,
      statMultipliers: {
        maxHp: 1.18,
        strength: 1.38,
        speed: 1.16,
        size: 1.08,
      },
      colorHex: 0xdc143c,
      emissiveHex: 0x990022,
      colorCss: '#dc143c',
      emissiveCss: '#990022',
      visualTag: 'crimson_fangs',
    },
    cryo_blood: {
      id: 'cryo_blood',
      name: 'Hémolymphe Cryogénique',
      shortLabel: 'Cryo / Givre',
      description:
        'Cristaux de givre dorsaux ralentissant le métabolisme basal (résistance aux famines) tout en renforçant la vigueur.',
      dominant: true,
      fitnessBonus: 0.36,
      metabolismCost: 0.8,
      statMultipliers: {
        maxHp: 1.3,
        strength: 1.22,
        speed: 1.05,
        size: 1.1,
      },
      colorHex: 0x00e5ff,
      emissiveHex: 0x0088cc,
      colorCss: '#00e5ff',
      emissiveCss: '#0088cc',
      visualTag: 'ice_spikes',
    },
    winged_leap: {
      id: 'winged_leap',
      name: 'Membranes Alaires',
      shortLabel: 'Ailé',
      description:
        'Excroissances membraneuses dorsales permettant des bonds fulgurants et une dispersion rapide entre biomes.',
      dominant: true,
      fitnessBonus: 0.35,
      metabolismCost: 1.12,
      statMultipliers: {
        maxHp: 1.0,
        strength: 1.15,
        speed: 1.42,
        size: 1.06,
      },
      colorHex: 0xffb300,
      emissiveHex: 0xcc7700,
      colorCss: '#ffb300',
      emissiveCss: '#cc7700',
      visualTag: 'membrane_wings',
    },
    titan_growth: {
      id: 'titan_growth',
      name: 'Gigantisme Titanesque',
      shortLabel: 'Titan',
      description:
        'Hypertrophie hormonale héréditaire décuplant la carrure, la vitalité et la force brute au prix d’un appétit colossal.',
      dominant: true,
      fitnessBonus: 0.48,
      metabolismCost: 1.35,
      statMultipliers: {
        maxHp: 1.65,
        strength: 1.5,
        speed: 0.92,
        size: 1.35,
      },
      colorHex: 0xffd700,
      emissiveHex: 0xd48800,
      colorCss: '#ffd700',
      emissiveCss: '#d48800',
      visualTag: 'titan_runes',
    },
    amphibious_lungs: {
      id: 'amphibious_lungs',
      name: 'Pattes & Branchies Amphibies',
      shortLabel: 'Amphibie',
      description:
        'Membres locomoteurs amphibies musclés et poumons pressurisés permettant aux prédateurs marins (Requins Marcheurs) d’envahir la terre ferme avec une vitesse et une vitalité accrues.',
      dominant: true,
      fitnessBonus: 0.42,
      metabolismCost: 1.08,
      statMultipliers: {
        maxHp: 1.2,
        strength: 1.22,
        speed: 1.2,
        size: 1.12,
      },
      colorHex: 0x00a8ff,
      emissiveHex: 0x0055aa,
      colorCss: '#00a8ff',
      emissiveCss: '#0055aa',
      visualTag: 'amphibious_fins',
    },
  },

  /**
   * Central Sanctuary Bastion Parameters
   */
  BASTION: {
    POS: { x: 0, z: 0 },
    RADIUS: 14,
    INITIAL_HP: 500,
    MAX_HP: 500,
    HEAL_RATE: 15,
    STRUCTURES: {
      watchtower: {
        id: 'watchtower',
        name: 'Tour de Guet',
        woodCost: 25,
        crystalCost: 10,
        range: 34,
        damage: 16,
        fireInterval: 1.4,
      },
      palisade: {
        id: 'palisade',
        name: 'Palissade Runique',
        woodCost: 30,
        crystalCost: 5,
        hpBonus: 180,
        thornsDamage: 8,
      },
      biolab: {
        id: 'biolab',
        name: 'Bio-Laboratoire',
        woodCost: 20,
        crystalCost: 20,
        scoutVisionBonus: 12,
      },
    },
  },

  /**
   * Scout (Éclaireur) & Allied NPC Parameters
   */
  SCOUT: {
    SPEED: 13,
    VISION_RADIUS: 34,
    FLEE_RADIUS: 16,
    HP: 60,
    PATROL_MIN_RADIUS: 45,
    PATROL_MAX_RADIUS: 105,
  },

  /**
   * Player Base Attributes
   */
  PLAYER: {
    MAX_HP: 160,
    SPEED: 13.5,
    DASH_SPEED: 30,
    DASH_DURATION: 0.22,
    DASH_COOLDOWN: 1.4,
    CLEAVE_DAMAGE: 32,
    CLEAVE_RANGE: 5.2,
    CLEAVE_COOLDOWN: 0.42,
    INTERACT_RADIUS: 5.5,
  },

  /**
   * Roguelike Level-Up Counter-Adaptation Upgrade Cards for the Player
   */
  UPGRADES: [
    {
      id: 'cleave_damage',
      designId: 'patient_zero_tracker',
      name: 'Traqueur de Patient Zéro',
      category: 'Traque Génétique',
      counterTarget: 'Lignées Mutantes & Patients Zéro',
      description:
        '+10% dégâts de fente (Cleave), +12% dégâts contre les Mutants/Hybrides et +10% vitesse vers une mutation repérée.',
      icon: '🎯',
      bonus: {
        cleaveDamageMult: 1.1,
        mutantDamageMult: 1.12,
        towardMutantSpeedMult: 1.1,
      },
    },
    {
      id: 'move_speed',
      designId: 'strider_boots',
      name: 'Bottes d’Expédition Véloce',
      category: 'Mobilité',
      counterTarget: 'Course contre le Compte à Rebours Eco-Tick',
      description:
        '+8% vitesse de déplacement et réduction de 15% du temps de recharge d’esquive pour traverser l’île avant un Eco-Tick.',
      icon: '🥾',
      bonus: { speedMult: 1.08, dashCooldownMult: 0.85 },
    },
    {
      id: 'max_hp_regen',
      designId: 'amber_blood_vigor',
      name: 'Sang d’Ambre Régénérant',
      category: 'Survie',
      counterTarget: 'Guerre d’Usure en Terres Sauvages',
      description:
        '+15 PV Maximum, restauration immédiate de 25 PV et régénération passive de +1.0 PV/s.',
      icon: '❤️',
      bonus: { maxHpFlat: 15, healInstant: 25, regenPerSec: 1.0 },
    },
    {
      id: 'scout_vision',
      designId: 'scout_falconry',
      name: 'Fauconnerie d’Éclaireur',
      category: 'Renseignement',
      counterTarget: 'Détection Précoce en Deep Wilderness',
      description:
        '+12% portée de vision des Éclaireurs au-delà de la frontière et +10% vitesse d’expédition et de fuite.',
      icon: '🦅',
      bonus: { scoutVisionMult: 1.12, scoutSpeedMult: 1.1 },
    },
    {
      id: 'bastion_turret_power',
      designId: 'thorn_bulwark',
      name: 'Muraille d’Épines & Balistes Runiques',
      category: 'Bastion',
      counterTarget: 'Migrations de Famine (Surpopulation > 6)',
      description:
        '+12% dégâts des Gardes et Tours de Guet, +60 PV au Bastion et +6 dégâts d’épines.',
      icon: '🏰',
      bonus: { turretDamageMult: 1.12, bastionHpBonus: 60, bastionThornsAdd: 6 },
    },
    {
      id: 'fire_resist',
      designId: 'pyrophage_blade',
      name: 'Lame Pyrophage & Égide Cryo',
      category: 'Contre-Mutation',
      counterTarget: 'Troll de Feu & Dragons Volcaniques',
      description:
        'Réduit de 8% les dégâts subis des mutants élémentaires (Feu/Venin/Givre), élargit l’arc d’attaque de +0.5m et +8% dégâts.',
      icon: '🛡️',
      bonus: { damageReduction: 0.08, cleaveRangeAdd: 0.5, cleaveDamageMult: 1.08 },
    },
    {
      id: 'juvenile_purge',
      designId: 'juvenile_purge',
      name: 'Purge Juvénile & Terre Brûlée',
      category: 'Écologie Conway',
      counterTarget: 'Cellules à Densité Optimale (2–5)',
      description:
        'Tuer un mutant ou un Bébé monstre draine 12% de la biomasse de sa cellule (+12% dégâts vs Bébés, +8% dégâts de fente).',
      icon: '🧬',
      bonus: { cellBiomassDrainOnKill: 0.12, babyDamageMult: 1.12, cleaveDamageMult: 1.08 },
    },
  ],

  /**
   * Phase 8 / Phase 11 — RPG Legendary Elemental Weapons Catalog (`ELEMENTAL_WEAPONS`)
   * Rebalanced in Phase 11: +10% to +12% base damage, +15% vs target clade.
   */
  ELEMENTAL_WEAPONS: {
    runic_steel: {
      id: 'runic_steel',
      name: 'Espadon Runique du Bastion',
      shortName: 'Espadon Runique',
      element: 'physical',
      icon: '⚔️',
      colorCss: '#dfe6e9',
      colorHex: 0xdfe6e9,
      emissiveHex: 0x636e72,
      slashColorHex: 0xf5f6fa,
      shrinePos: { x: 0, z: -6 },
      unlockedByDefault: true,
      cleaveDamageMult: 1.0,
      damageMultiplier: 1.0,
      cleaveRangeMult: 1.0,
      attackSpeedMult: 1.0,
      moveSpeedMult: 1.0,
      cladeBonusMultiplier: 1.0,
      lifestealRatio: 0.0,
      sparesHerbivores: false,
      biomassOnKill: 0,
      description:
        'Lame d’acier runique standard forgée au Sanctuaire. Équilibrée mais dépourvue d’affinité élémentaire.',
      passiveSummaryFR: 'Arme de départ équilibrée (Dégâts ×1.00, Portée ×1.00).',
    },
    fire_greatsword: {
      id: 'fire_greatsword',
      name: 'Lame Solaire d’Ignis',
      shortName: 'Lame de Feu',
      element: 'fire',
      icon: '🔥',
      colorCss: '#ff5252',
      colorHex: 0xff5252,
      emissiveHex: 0xff3838,
      slashColorHex: 0xff793f,
      shrinePos: { x: 34, z: -28 },
      unlockedByDefault: false,
      cleaveDamageMult: 1.12,
      damageMultiplier: 1.12,
      cleaveRangeMult: 1.05,
      attackSpeedMult: 1.0,
      moveSpeedMult: 1.0,
      burnDps: 8,
      burnDuration: 3.5,
      deathExplosionDamage: 18,
      deathExplosionRadius: 5.5,
      vsBeastAndMoleMult: 1.15,
      cladeBonusMultiplier: 1.15,
      lifestealRatio: 0.0,
      sparesHerbivores: false,
      biomassOnKill: 0,
      description:
        '+12% dégâts de fente, embrase les cibles (8 DPS pendant 3.5s), provoque une détonation solaire au kill et inflige +15% dégâts contre les Bêtes Sauvages & Taupes Géantes.',
      passiveSummaryFR:
        '🔥 +12% Dégâts • Brûlure (8 DPS/3.5s) • Explosion solaire au kill • +15% vs Bêtes & Taupes',
    },
    ice_greatsword: {
      id: 'ice_greatsword',
      name: 'Espadon Givré de Borée',
      shortName: 'Arme de Glace',
      element: 'ice',
      icon: '❄️',
      colorCss: '#00d2d3',
      colorHex: 0x00d2d3,
      emissiveHex: 0x0abde3,
      slashColorHex: 0x48dbfb,
      shrinePos: { x: -36, z: -26 },
      unlockedByDefault: false,
      cleaveDamageMult: 1.1,
      damageMultiplier: 1.1,
      cleaveRangeMult: 1.12,
      attackSpeedMult: 1.04,
      moveSpeedMult: 1.0,
      slowFactor: 0.65,
      slowDuration: 3.5,
      shattersOsteoArmor: true,
      vsPyroAndSharkMult: 1.15,
      cladeBonusMultiplier: 1.15,
      lifestealRatio: 0.0,
      sparesHerbivores: false,
      biomassOnKill: 0,
      description:
        '+10% dégâts et +12% portée de fente, inflige Givre (-35% vitesse pendant 3.5s), brise les Carapaces Ostéo-Dermiques et inflige +15% dégâts contre les Mutants Pyro (Feu) & Requins Marcheurs.',
      passiveSummaryFR:
        '❄️ +10% Dégâts • +12% Portée • Givre (-35% vitesse) • Brise-Carapace • +15% vs Mutants Feu & Requins',
    },
    lightning_greatsword: {
      id: 'lightning_greatsword',
      name: 'Glaive Foudroyant d’Aether',
      shortName: 'Arme de Foudre',
      element: 'lightning',
      icon: '⚡',
      colorCss: '#a29bfe',
      colorHex: 0xa29bfe,
      emissiveHex: 0x6c5ce7,
      slashColorHex: 0x74b9ff,
      shrinePos: { x: 38, z: 26 },
      unlockedByDefault: false,
      cleaveDamageMult: 1.1,
      damageMultiplier: 1.1,
      cleaveRangeMult: 1.06,
      attackSpeedMult: 1.12,
      moveSpeedMult: 1.08,
      chainTargets: 3,
      chainDamage: 12,
      chainRange: 11,
      vsGreenskinAndAquaticMult: 1.15,
      cladeBonusMultiplier: 1.15,
      lifestealRatio: 0.0,
      sparesHerbivores: false,
      biomassOnKill: 0,
      description:
        '+10% dégâts, +12% vitesse d’attaque et +8% vitesse de déplacement. Chaque coup déclenche un Éclair en Chaîne sur 3 ennemis proches (12 dégâts) et inflige +15% dégâts aux Peaux-Vertes & Amphibies.',
      passiveSummaryFR:
        '⚡ +10% Dégâts • +12% Vit. Attaque • +8% Vit. Course • Éclair (12 dég.) • +15% vs Gobelins/Orcs',
    },
    venom_greatsword: {
      id: 'venom_greatsword',
      name: 'Faux d’Émeraude Symbiotique',
      shortName: 'Arme de Venin & Biomasse',
      element: 'venom',
      icon: '🧪',
      colorCss: '#2ed573',
      colorHex: 0x2ed573,
      emissiveHex: 0x20bf6b,
      slashColorHex: 0x7bed9f,
      shrinePos: { x: -34, z: 30 },
      unlockedByDefault: false,
      cleaveDamageMult: 1.1,
      damageMultiplier: 1.1,
      cleaveRangeMult: 1.08,
      attackSpeedMult: 1.06,
      moveSpeedMult: 1.04,
      venomDps: 7,
      venomDuration: 4.0,
      enemyDamageDebuff: 0.15,
      vsBeastAndMoleMult: 1.15,
      cladeBonusMultiplier: 1.15,
      lifestealRatio: 0.08,
      sparesHerbivores: true,
      biomassOnKill: 1,
      description:
        '+10% dégâts, inflige un Venin Corrosif (7 DPS, -15% dégâts ennemis), confère 8% de Vol de Vie, ÉPARGNE AUTOMATIQUEMENT le Gibier Herbivore (0 dégât aux Biches/Lapins !) et récolte +1 Biomasse par monstre tué.',
      passiveSummaryFR:
        '🧪 +10% Dégâts • 8% Vol de Vie • Venin (7 DPS) • Immunité Gibier (Biches/Lapins épargnés) • +1 Biomasse/kill',
    },
  },

  /**
   * Phase 8 — 3 Ancient Relic Fragments & Planetary Island Shield Specification
   */
  RELIC_FRAGMENTS: {
    REQUIRED_COUNT: 3,
    SHIELD_DOME_RADIUS: 115,
    FRAGMENT_REWARD_XP: 50,
    FRAGMENT_REWARD_CRYSTAL: 15,
    SHRINES: [
      {
        id: 'relic_dawn_north',
        index: 1,
        name: 'Fragment d’Aube (Nord)',
        sectorLabel: 'Hautes Terres du Nord',
        pos: { x: 4, z: -64 },
        colorHex: 0x00e5ff,
        colorCss: '#00e5ff',
      },
      {
        id: 'relic_breakers_southeast',
        index: 2,
        name: 'Fragment des Brisants (Sud-Est)',
        sectorLabel: 'Littoral & Plaines du Sud-Est',
        pos: { x: 58, z: 42 },
        colorHex: 0xffd32a,
        colorCss: '#ffd32a',
      },
      {
        id: 'relic_caldera_southwest',
        index: 3,
        name: 'Fragment de Caldeira (Sud-Ouest)',
        sectorLabel: 'Lisière Volcanique Sud-Ouest',
        pos: { x: -56, z: 44 },
        colorHex: 0xff5e57,
        colorCss: '#ff5e57',
      },
    ],
  },

  /**
   * Phase 8 — Multi-Island Campaign Progression Tiers (`Île 1 -> Île 2 -> Île 3...`)
   */
  ISLAND_TIERS: [
    {
      islandNumber: 1,
      name: 'Île 1 : Archipel d’Émeraude',
      subtitle: 'Berceau du Bastion & Premières Mutations',
      enemyStatMultiplier: 1.0,
      mutationRateBonus: 0.0,
      initialMutantCount: 1,
      sharkLandingTimeSec: 40,
      moleEruptionTimeSec: 65,
      skyTintHex: 0x87ceeb,
    },
    {
      islandNumber: 2,
      name: 'Île 2 : Caldeira des Abysses',
      subtitle: 'Débarquements Amphibies Accélérés & Lignées Hybrides',
      enemyStatMultiplier: 1.35,
      mutationRateBonus: 0.04,
      initialMutantCount: 3,
      sharkLandingTimeSec: 24,
      moleEruptionTimeSec: 38,
      skyTintHex: 0x54a0ff,
    },
    {
      islandNumber: 3,
      name: 'Île 3 : Terres Mutantes d’Obsidienne',
      subtitle: 'Sélection Darwinienne Extrême & Prédateurs Poly-Mutants',
      enemyStatMultiplier: 1.75,
      mutationRateBonus: 0.08,
      initialMutantCount: 5,
      sharkLandingTimeSec: 16,
      moleEruptionTimeSec: 26,
      skyTintHex: 0x5f27cd,
    },
    {
      islandNumber: 4,
      name: 'Île 4 : Sanctuaire Draconique Primordial',
      subtitle: 'L’Épreuve Ultime des Souverains Apex',
      enemyStatMultiplier: 2.2,
      mutationRateBonus: 0.12,
      initialMutantCount: 7,
      sharkLandingTimeSec: 12,
      moleEruptionTimeSec: 18,
      skyTintHex: 0xff5252,
    },
  ],
};

export default CONFIG;
